// Expo config-plugin: injects GoogleSignIn URL handling into the
// ExpoAppDelegate-based Swift AppDelegate generated by `expo prebuild`.
//
// Why we need this: RN 0.77+ stopped auto-swizzling URL handlers in the Swift
// AppDelegate, and the official `@react-native-google-signin/google-signin`
// plugin only writes the reversed-client-id URL scheme to Info.plist. Without
// the manual `GIDSignIn.sharedInstance.handle(url)` call inside
// `application(_:open:options:)`, the Google Sign-In sheet opens but the
// callback URL is never delivered back to GIDSignIn, and the sign-in promise
// never resolves.
//
// We must inject this every prebuild because `expo prebuild --clean` wipes
// `ios/Memoura/AppDelegate.swift`.
const { withAppDelegate } = require('expo/config-plugins');

const IMPORT_LINE = 'import GoogleSignIn';
const HANDLER_LINE = 'if GIDSignIn.sharedInstance.handle(url) { return true }';

const withGoogleSigninUrlHandler = (config) => {
  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        '[withGoogleSigninUrlHandler] expected Swift AppDelegate but got ' +
          cfg.modResults.language,
      );
    }

    let contents = cfg.modResults.contents;

    if (!contents.includes(IMPORT_LINE)) {
      contents = contents.replace(
        /import ReactAppDependencyProvider/,
        `import ReactAppDependencyProvider\n${IMPORT_LINE}`,
      );
    }

    if (!contents.includes('GIDSignIn.sharedInstance.handle(url)')) {
      const openUrlReturn =
        'return super.application(app, open: url, options: options) || RCTLinkingManager.application(app, open: url, options: options)';
      if (!contents.includes(openUrlReturn)) {
        throw new Error(
          '[withGoogleSigninUrlHandler] could not find open(url:) return — AppDelegate template changed',
        );
      }
      contents = contents.replace(
        openUrlReturn,
        `${HANDLER_LINE}\n    ${openUrlReturn}`,
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
};

module.exports = withGoogleSigninUrlHandler;
