export { ActionsTraySlide } from './ActionsTraySlide';
export { ClosingSlide } from './ClosingSlide';
export { CoverSlide } from './CoverSlide';
export { FirstsSlide } from './FirstsSlide';
export { LetterSlide } from './LetterSlide';
export { PlacesSlide } from './PlacesSlide';
export { StatSlide } from './StatSlide';
export { TopMomentSlide } from './TopMomentSlide';
export { TopQuestionSlide } from './TopQuestionSlide';
